openapi: 3.1.1
info:
  title: StorageManager Management API
  description: API for managing sites, including areas, modules, and devices.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Development server

paths:
  /sites:
    get:
      summary: Get all sites
      operationId: getAllSites
      responses:
        '200':
          description: Successfully retrieved all sites
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
        '500':
          description: Internal server error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    post:
      summary: Create a new site
      operationId: createSite
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteCreateRequest'
      responses:
        '201':
          description: Site successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Site'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

  /sites/{siteId}:
    get:
      summary: Get a single site by ID
      operationId: getSiteById
      parameters:
        - name: siteId
          in: path
          required: true
          description: The ID of the site
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved site
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Site'
        '404':
          description: Site not found
        '500':
          description: Internal server error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    put:
      summary: Update an existing site
      operationId: updateSite
      parameters:
        - name: siteId
          in: path
          required: true
          description: The ID of the site to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteUpdateRequest'
      responses:
        '200':
          description: Successfully updated site
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Site'
        '400':
          description: Bad request
        '404':
          description: Site not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

    delete:
      summary: Delete a site by ID
      operationId: deleteSite
      parameters:
        - name: siteId
          in: path
          required: true
          description: The ID of the site to delete
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted site
        '404':
          description: Site not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

components:
  schemas:
    Site:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the site
        name:
          type: string
          description: The name of the site
        description:
          type: string
          description: A brief description of the site
        numberOfAreas:
          type: integer
          description: The number of areas within the site
        numberOfModules:
          type: integer
          description: The number of modules within the site
        numberOfDevices:
          type: integer
          description: The total number of devices associated with the site

    SiteCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the site
        description:
          type: string
          description: A brief description of the site
      required:
        - name

    SiteUpdateRequest:
      type: object
      properties:
        name:
          type: string
          description: The updated name of the site
        description:
          type: string
          description: The updated description of the site
